# Generated by Django 4.0.2 on 2022-02-14 04:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Workday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('sector', models.CharField(max_length=20, null=True)),
                ('FBP_payroll', models.CharField(default='$', max_length=5)),
                ('AMCO_payroll', models.CharField(default='$', max_length=5)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workday.location')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.profile')),
            ],
        ),
    ]
