# Generated by Django 4.0.2 on 2022-02-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workday', '0002_location_remove_workday_id_remove_workday_user_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Location',
            new_name='location',
        ),
    ]
